apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-01
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/nitin8147/apache-spark.git
          revision: HEAD
          files:
          - path: "argocd/configs/*-config.yaml"
      - list:
          elements:
          - cluster: kind-kind
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{ release_name }}"
      namespace: "{{ namespace }}"
      labels: 
        name: "{{ release_name }}"
    spec:
      project: default
      sources:
      - repoURL: "{{ helm_repo_url }}"
        chart: "{{ chart_name }}"
        targetRevision: "{{ chart_version }}"
        helm:
          valueFiles: 
          - $values/{{ helm_value_file }}
          values: |
            "{{ helm_custom_values }}"
      - repoURL: "{{ value_file_repo }}"
        targetRevision: "{{ target_branch_values }}"
        ref: values

      destination:
        server: "{{ url }}"
        namespace: "{{ namespace }}"
      
      syncPolicy:
        automated: 
          selfHeal: true
        syncOptions:
        - ApplyOutofSyncOnly=true

      
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas
